version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_USER: &db-user "jexactyl"
    MYSQL_PASSWORD: &db-password ${MYSQL_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  panel:
    &panel-environment
    APP_URL: ${APP_URL}
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "Europe/Athens"
    APP_SERVICE_AUTHOR: ${EMAIL}
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    LE_EMAIL: ${LE_EMAIL}
  mail:
    &mail-environment
    MAIL_FROM: ${EMAIL}
    MAIL_DRIVER: "smtp"
    MAIL_HOST: ${EMAIL_HOST}
    MAIL_PORT: ${EMAIL_PORT}
    MAIL_USERNAME: ${EMAIL_USERNAME}
    MAIL_PASSWORD: ${EMAIL_PASSWORD}
    MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "jexactyl_database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: *db-user
  cache:
    image: redis:alpine
    restart: always
  panel:
    #image: ghcr.io/jexactyl/jexactyl:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    networks:
      - nginx-network
    links:
      - database
      - cache
    volumes:
      - "jexactyl_var:/app/var/"
      - "jexactyl_nginx:/etc/nginx/http.d/"
      - "jexactyl_certs:/etc/letsencrypt/"
      - "jexactyl_logs:/app/storage/logs"
      # - "/etc/ssl/certs:/etc/ssl/certs:ro"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_USERNAME: *db-user
volumes:
  jexactyl_database:
  jexactyl_var:
  jexactyl_nginx:
  jexactyl_certs:
  jexactyl_logs:
networks:
  default:
    ipam:
      config:
        - subnet: 172.19.0.0/16
  nginx-network:
    external: true
    name: nginx-network
